#!/bin/bash

export	WORK_BASE=C:/work/workspace/JIS_ACP-8.8.5_Lead_TC38XQ
TEST_SEQUENCE=${PWD%/*}
export	TEST_SEQUENCE=${TEST_SEQUENCE##*/}\
	TARGET=${TARGET:=TRICORE}\
	DERIVATE=${DERIVATE:=TC38XQ}\
	TOOLCHAIN=${TOOLCHAIN:=tasking}\
	TOOLPATH_COMPILER=${TOOLPATH_COMPILER:=C:/work/workspace/JIS_ACP-8.8.5_Lead_TC38XQ/tools/toolchain/ctc}\
	TRESOS_BASE=${TRESOS_BASE:=${WORK_BASE}/Tresos}\
	PLUGINS_BASE=${PLUGINS_BASE:=$TRESOS_BASE/plugins}\
	TOOLS_BASE=${TOOLS_BASE:=${WORK_BASE}/tools}\
\
	TEST_BASE=${WORK_BASE}/tests\
	LOG_BASE=${WORK_BASE}/TestProtocols/LogBase\
	TESTPROTOCOLS_PATH=${WORK_BASE}/TestProtocols\
	MISRA_MODULE=ApplTemplates\
	MODULE_NAME=ApplTemplates\
	INTERNAL_MODULE_NAME=asc_ApplTemplates\
	MODULE_VARIANT=TS_TxDxM6I8R0\
	MODULE_ID=ApplTemplates_TS_TxDxM6I8R0


[ -z "${TOOLPATH_COMPILER}" ] || export PATH="${PATH:${TOOLPATH_COMPILER}/bin:${TOOLPATH_COMPILER}/lib"

