/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.4.7
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2020 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.4.7
 * on Sun Feb 14 07:12:40 EET 2021. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_ServiceSwComponentSecOC.h>

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentSecOC_PS_TxFreshnessManagement_GetTxFreshness (uint16 freshnessValueId, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) freshnessValue, P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) freshnessValueLength)
{
  /* suppress compiler warnings about unused arguments */
  (void)freshnessValueId;
  (void)freshnessValue;
  (void)*freshnessValueLength;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentSecOC_PS_TxFreshnessManagement_GetTxFreshness (uint16 freshnessValueId, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) freshnessValue, P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) freshnessValueLength) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentSecOC_PS_TxFreshnessManagement_SPduTxConfirmation (uint16 freshnessValueId)
{
  /* suppress compiler warnings about unused arguments */
  (void)freshnessValueId;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentSecOC_PS_TxFreshnessManagement_SPduTxConfirmation (uint16 freshnessValueId) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentSecOC_PS_RxFreshnessManagement_GetRxFreshness (uint16 freshnessValueId, P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) truncatedFreshnessValue, uint32 truncatedFreshnessLength, uint16 authVerifyAttempts, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) freshnessValue, P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) freshnessValueLength)
{
  /* suppress compiler warnings about unused arguments */
  (void)freshnessValueId;
  (void)truncatedFreshnessValue;
  (void)truncatedFreshnessLength;
  (void)authVerifyAttempts;
  (void)freshnessValue;
  (void)*freshnessValueLength;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentSecOC_PS_RxFreshnessManagement_GetRxFreshness (uint16 freshnessValueId, P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) truncatedFreshnessValue, uint32 truncatedFreshnessLength, uint16 authVerifyAttempts, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) freshnessValue, P2VAR(uint32, AUTOMATIC, RTE_APPL_DATA) freshnessValueLength) */

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
