/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \version 6.8.4
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2022 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.8.4
 * on Thu Aug 31 18:00:56 CST 2023. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_SWC_IoHwAbs.h>
#include <Dio_Cfg.h>
#include <Dio.h>
#include <ComM.h>

#define DIO_HIGH_VALUE 1U
#define DIO_LOW_VALUE 0U


int flag = 1u;
int Count = 0u;
#define Dio_LevelType uint8

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
#define SWC_IoHwAbs_START_SEC_CODE
#include <SWC_IoHwAbs_MemMap.h>
FUNC(void, RTE_CODE) LedControl_IO (void)
{
  
  ComM_RequestComMode(ComMConf_ComMChannel_CanNetwork,COMM_FULL_COMMUNICATION);
  Count++;
  if(flag)
  {
    Dio_WriteChannel(DioConf_DioChannel_MY_LED_CYCLIC, (Dio_LevelType) DIO_HIGH_VALUE);
  }
  else
  {
    Dio_WriteChannel(DioConf_DioChannel_MY_LED_CYCLIC, (Dio_LevelType) DIO_LOW_VALUE);
  }

  if(Count == 50)
  {
    flag = ~flag;
	  Count= 0;
  }

} /* FUNC(void, RTE_CODE) LedControl_IO (void) */

#define SWC_IoHwAbs_STOP_SEC_CODE
#include <SWC_IoHwAbs_MemMap.h>

#define SWC_IoHwAbs_START_SEC_CODE
#include <SWC_IoHwAbs_MemMap.h>
FUNC(void, RTE_CODE) SWC_IoHwAbs_SetDiscreteValue (uint32 pdav0, uint32 value)
{
  /* suppress compiler warnings about unused arguments */
  (void)pdav0;
  (void)value;

} /* FUNC(void, RTE_CODE) SWC_IoHwAbs_SetDiscreteValue (uint32 pdav0, uint32 value) */

#define SWC_IoHwAbs_STOP_SEC_CODE
#include <SWC_IoHwAbs_MemMap.h>

/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
