/**
 * \file
 *
 * \brief AUTOSAR Rte
 *
 * This file contains the implementation of the AUTOSAR
 * module Rte.
 *
 * \author Elektrobit Automotive GmbH, 91058 Erlangen, Germany
 *
 * Copyright 2005 - 2018 Elektrobit Automotive GmbH
 * All rights exclusively reserved for Elektrobit Automotive GmbH,
 * unless expressly agreed to otherwise.
 */

/*
 * This file contains an Rte component template / example code
 *
 * This file has been automatically generated by
 * EB tresos AutoCore Rte Generator Version 6.2.19
 * on Mon Jul 02 14:12:39 EEST 2018. !!!IGNORE-LINE!!!
 */

/*
 * \addtogroup Rte Runtime Environment
 * @{
 */

/* ==================[Includes]=============================================== */
#include <Rte_ServiceSwComponentDem.h>

/* ==================[Definition of functions with external linkage]========== */
/* ------------------------[runnable entity skeletons]------------------------ */
FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDem_CBReadData_DemExternalCSDataElementClass_Session_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data)
{
  /* suppress compiler warnings about unused arguments */
  (void)Data;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDem_CBReadData_DemExternalCSDataElementClass_Session_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data) */

FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDem_CBReadData_DemExternalCSDataElementClass_ExtDataRec_0x01_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data)
{
  /* suppress compiler warnings about unused arguments */
  (void)Data;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDem_CBReadData_DemExternalCSDataElementClass_ExtDataRec_0x01_ReadData (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data) */


FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDem_SetClearDTC_master_SetClearDTC (uint32 DTC, Dem_DTCFormatType DTCFormat, Dem_DTCOriginType DTCOrigin)
{
  /* suppress compiler warnings about unused arguments */
  (void)DTC;
  (void)DTCFormat;
  (void)DTCOrigin;
  return RTE_E_OK;
} /* FUNC(Std_ReturnType, RTE_CODE) ServiceSwComponentDem_SetClearDTC_master_SetClearDTC (uint32 DTC, Dem_DTCFormatType DTCFormat, Dem_DTCOriginType DTCOrigin) */


/*
  ------------------------[runnable-independent API]-------------------------

  Copy and paste the following API to those runnable entity functions where
  you want to use them.

  ------------------------[port handle API]----------------------------------
  ------------------------[per instance memory API]--------------------------
 */

/** @} doxygen end group definition  */
/* ==================[end of file]============================================ */
